castelao/GSW-rs

Cargo.toml

Open space to organize auxiliary packages.

feat: Moving to a workspace structure (root package)

---

Cargo.toml
src/volume.rs

Cleaning and organizing module volume. I believe that we started the crate with this module, and we were still figuring out how we wanted to organize this crate and some standards. It's time to review this module, re-organize and clean it.

Cleaning volume

---

src/gsw_internal_const.rs
src/volume.rs

Adding some missing functions in the volume module.

[WIP] Extending volume

---

.github/workflows/gsw-python.yml
src/ffi.rs
src/practical_salinity.rs
src/volume.rs

Add new functions from #25 to the FFI

Extending volume (in the FFI)

---

src/volume.rs
tests/volume.rs

Validating more functions with the dataset of reference.

Volume validation

---

.github/workflows/bench.yml
Cargo.lock
Cargo.toml
benches/volume.rs
flake.nix

Benchmarks for all functions exposed in the FFI.

[MRG] Add initial benchmarks with criterion

---

benches/volume.rs
src/ffi.rs

[MRG] Feat: Add new functions from #36

---

Cargo.lock
Cargo.toml

regex vulnerability, indirect dependency.

Addressing CVE 2022 24713

---

Cargo.lock
Cargo.toml
src/earth.rs
src/error.rs

- Documenting
- References
- More tests

Improving earth module

---

README.md
src/lib.rs
src/volume.rs

Minor improvements to volume functions.

Improving volume docs

---

README.md
src/lib.rs

Addressing the citing issue raised by @PaulMBarker on TEOS-10/GSW-C#56
Although we have a list of references recorded in our DOI, it is not a bad idea to recommend our users to cite (and hopefully actually read it) TEOS-10 report and how to use the Toolbox.

Extending citing recommendations

---

.github/workflows/ci.yml

Updating codecov-action

---

.github/workflows/ci.yml
Cargo.lock
README.md

Upgrading min Rust version to 1.64

Fix predicates

---

Cargo.lock
Cargo.toml

New function gsw_internal_funcs::gibbs_ice(), thanks to @brycemines.

Bump version 0.1.2

---

CITATION.cff
Cargo.lock
Cargo.toml
README.md
src/lib.rs

We do too many extra things here. Anyone new to Rust would be overwhelmed, so let's give some hints on how to understand it.

Explaining the repository contents

---

Cargo.lock
Cargo.toml
README.md
src/conversions.rs
src/gsw_internal_funcs/mod.rs
src/lib.rs
src/practical_salinity.rs

Missing documentation for module conversion

Conversion documentation

---

README.md

Anyone new to Rust might feel lost how to start. Let's give a minumum guidance here.

Minimum guidance on how to use the crate

---

.github/workflows/build_nix.yml
Cargo.lock
Cargo.toml

Adding metadata and updating dependencies.

Updating crate

---

README.md

In response to #63, some explanation for why in Rust?

Why re-write it in Rust

---

Cargo.lock
Cargo.toml

Bump version 0.2.2
